default: &default
  password: somepass
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: postgres
  password: <%= ENV.fetch('ADS_DATABASE_PASSWORD') { 'mysecretpassword' } %>
  timeout: 5000
  # url: <%= ENV['DATABASE_URL'] %>
  # socket: /tmp/.s.PGSQL.5432
development:
  <<: *default
  database: ads_backend_development
  host: localhost
test:
  <<: *default
  database: ads_backend_test
production:
  <<: *default
  database: ads_backend_production
