default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] { 'localhost' } %>
  port: <%= ENV['DATABASE_PORT'] { 5432 } %>
  username: <%= ENV['DATABASE_USER'] { 'postgres' } %>
  password: <%= ENV['DATABASE_PASSWORD'] { 'mysecretpassword' } %>
  pool: <%= ENV['RAILS_MAX_THREADS'] { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: ads_backend_development
test:
  <<: *default
  database: ads_backend_test
production:
  <<: *default
  database: ads_backend_production
